# Generated by Django 4.2.11 on 2024-03-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='filename',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
